services:
  arma-reforger:
    image: soda3x/docker-reforger-server:latest
    platform: linux/amd64
    container_name: arma-reforger
    build:
      context: .
    ports:
      - "2001:2001/udp"
      - "17777:17777/udp"
      - "19999:19999/udp" # RCON
    volumes:
      - ./reforger/configs:/home/reforger/configs
      - ./reforger/profile:/home/reforger/profile
      - ./reforger/workshop:/home/reforger/workshop
    environment:
      - CONFIG=myconfig # Name of your config (without path or .json extension)
      - USE_EXPERIMENTAL=false # Set to true to use Experimental branch of Reforger server
      - MAX_FPS=60 # Limit the FPS of your server
      - STARTUP_PARAMETERS="-nds 1 -nwkResolution 500" # Add as many additional startup parameters as needed
      - MAX_RESTARTS=3 # Adds a maximum number of auto-restart attempts before giving up (When empty defaults to infinite attempts)
